import {
  INDUSTRY_OPTIONS,
  COUNTRY_OPTIONS,
  HEARD_ABOUT_OPTIONS,
  AREA_OF_INTEREST_OPTIONS,
  TIMEZONE_OPTIONS,
} from "./formOptions";

// One entry per sample form. `type` drives which input DummyForm renders;
// `options` is only read for type "select". Every form ends with the same
// privacy-policy checkbox and its own submit label.
export const FORMS = [
  {
    id: "request-rfp",
    title: "Request an RFP",
    description: "Tell us about your requirements and our team will get back to you.",
    submitLabel: "Submit RFP Request",
    fields: [
      { name: "firstName", label: "First Name", type: "text", required: true },
      { name: "lastName", label: "Last Name", type: "text", required: true },
      { name: "companyName", label: "Company Name", type: "text", required: true },
      { name: "businessEmail", label: "Business Email", type: "email", required: true },
      { name: "phoneNumber", label: "Phone Number", type: "tel" },
      { name: "jobTitle", label: "Job Title", type: "text" },
      { name: "industry", label: "Industry", type: "select", required: true, options: INDUSTRY_OPTIONS },
      { name: "country", label: "Country / Region", type: "select", required: true, options: COUNTRY_OPTIONS },
      { name: "projectName", label: "RFP / Project Name", type: "text", required: true },
      { name: "projectDescription", label: "Project Description", type: "textarea", required: true },
      { name: "startDate", label: "Expected Project Start Date", type: "date" },
      { name: "budget", label: "Estimated Budget", type: "text", placeholder: "e.g. $50,000 - $100,000" },
      { name: "rfpDocument", label: "Upload RFP / Requirements Document", type: "file" },
      { name: "heardAboutUs", label: "How did you hear about us?", type: "select", options: HEARD_ABOUT_OPTIONS },
    ],
  },
  {
    id: "talk-to-expert",
    title: "Talk to an Expert",
    description: "Connect with one of our experts to discuss your business needs.",
    submitLabel: "Talk to an Expert",
    fields: [
      { name: "firstName", label: "First Name", type: "text", required: true },
      { name: "lastName", label: "Last Name", type: "text", required: true },
      { name: "companyName", label: "Company Name", type: "text", required: true },
      { name: "businessEmail", label: "Business Email", type: "email", required: true },
      { name: "phoneNumber", label: "Phone Number", type: "tel", required: true },
      { name: "jobTitle", label: "Job Title", type: "text" },
      { name: "industry", label: "Industry", type: "select", options: INDUSTRY_OPTIONS },
      { name: "areaOfInterest", label: "Area of Interest", type: "select", required: true, options: AREA_OF_INTEREST_OPTIONS },
      { name: "discussTopic", label: "What would you like to discuss?", type: "textarea", required: true },
      { name: "contactMethod", label: "Preferred Contact Method", type: "select", options: ["Email", "Phone", "Video Meeting"] },
      { name: "additionalInfo", label: "Additional Information", type: "textarea" },
    ],
  },
  {
    id: "solution-assessment",
    title: "Request a Solution Assessment",
    description: "Let our experts understand your current environment and identify potential solutions.",
    submitLabel: "Request Assessment",
    fields: [
      { name: "firstName", label: "First Name", type: "text", required: true },
      { name: "lastName", label: "Last Name", type: "text", required: true },
      { name: "companyName", label: "Company Name", type: "text", required: true },
      { name: "businessEmail", label: "Business Email", type: "email", required: true },
      { name: "phoneNumber", label: "Phone Number", type: "tel", required: true },
      { name: "jobTitle", label: "Job Title", type: "text" },
      { name: "industry", label: "Industry", type: "select", required: true, options: INDUSTRY_OPTIONS },
      { name: "currentSolution", label: "Current Solution / Technology", type: "text" },
      { name: "businessChallenge", label: "Business Challenge", type: "textarea", required: true },
      { name: "assessmentRequirements", label: "Assessment Requirements", type: "textarea", required: true },
      { name: "desiredOutcomes", label: "Desired Outcomes", type: "textarea", required: true },
      { name: "preferredDate", label: "Preferred Assessment Date", type: "date" },
      { name: "additionalInfo", label: "Additional Information", type: "textarea" },
      { name: "supportingDocs", label: "Upload Supporting Documents", type: "file" },
    ],
  },
  {
    id: "schedule-meeting",
    title: "Schedule a Meeting",
    description: "Choose a convenient time to connect with our team.",
    submitLabel: "Schedule Meeting",
    fields: [
      { name: "firstName", label: "First Name", type: "text", required: true },
      { name: "lastName", label: "Last Name", type: "text", required: true },
      { name: "companyName", label: "Company Name", type: "text", required: true },
      { name: "businessEmail", label: "Business Email", type: "email", required: true },
      { name: "phoneNumber", label: "Phone Number", type: "tel" },
      { name: "meetingTopic", label: "Meeting Topic", type: "text", required: true },
      { name: "preferredDate", label: "Preferred Date", type: "date", required: true },
      { name: "preferredTime", label: "Preferred Time", type: "time", required: true },
      { name: "timeZone", label: "Time Zone", type: "select", required: true, options: TIMEZONE_OPTIONS },
      { name: "meetingType", label: "Meeting Type", type: "select", options: ["Video Meeting", "Phone Call", "In-person Meeting"] },
      { name: "additionalNotes", label: "Additional Notes", type: "textarea" },
    ],
  },
  {
    id: "customer-support",
    title: "Customer Support",
    description: "Submit your support request and our team will assist you.",
    submitLabel: "Submit Support Request",
    fields: [
      { name: "accountName", label: "Customer / Account Name", type: "text", required: true },
      { name: "contactName", label: "Contact Name", type: "text", required: true },
      { name: "businessEmail", label: "Business Email", type: "email", required: true },
      { name: "phoneNumber", label: "Phone Number", type: "tel" },
      { name: "accountId", label: "Customer / Account ID", type: "text" },
      { name: "productOrService", label: "Product / Service", type: "text", required: true },
      {
        name: "supportCategory",
        label: "Support Category",
        type: "select",
        required: true,
        options: ["Technical Issue", "Product Issue", "Service Issue", "Account / Billing", "Other"],
      },
      { name: "priority", label: "Priority", type: "select", required: true, options: ["Low", "Medium", "High", "Critical"] },
      { name: "issueSummary", label: "Issue Summary", type: "text", required: true },
      { name: "detailedDescription", label: "Detailed Description", type: "textarea", required: true },
      { name: "stepsTaken", label: "Steps Already Taken", type: "textarea" },
      { name: "screenshots", label: "Upload Screenshot / Documents", type: "file" },
      { name: "ticketNumber", label: "Existing Ticket Number", type: "text" },
    ],
  },
  {
    id: "escalation-reporting",
    title: "Escalation & Reporting",
    description: "Use this form to escalate an existing issue or report a customer-impacting concern.",
    submitLabel: "Submit Escalation",
    fields: [
      { name: "accountName", label: "Customer / Account Name", type: "text", required: true },
      { name: "contactName", label: "Contact Name", type: "text", required: true },
      { name: "businessEmail", label: "Business Email", type: "email", required: true },
      { name: "phoneNumber", label: "Phone Number", type: "tel" },
      { name: "ticketNumber", label: "Existing Ticket / Case Number", type: "text", required: true },
      { name: "issueCategory", label: "Issue Category", type: "text", required: true },
      { name: "currentIssue", label: "Current Issue", type: "textarea", required: true },
      { name: "previousActions", label: "Previous Support Actions", type: "textarea", required: true },
      { name: "businessImpact", label: "Business Impact", type: "textarea", required: true },
      { name: "severity", label: "Severity", type: "select", required: true, options: ["Medium", "High", "Critical"] },
      { name: "requestedResolution", label: "Requested Resolution", type: "textarea", required: true },
      { name: "additionalComments", label: "Additional Comments", type: "textarea" },
      { name: "supportingDocs", label: "Upload Supporting Documents", type: "file" },
    ],
  },
];
